image: python:3.7

before_script:
  - pip install tox setuptools qualifier
cache:
  paths:
  - /root/.cache
stages:
  - build

build:
  stage: build
  script:
    - update_qualifier --no-use-git --branch-name "$CI_COMMIT_REF_NAME" --tag-name "$CI_COMMIT_TAG"
    - tox
  artifacts:
    paths:
      - dist/
